#!/bin/bash

usage=$(cat << EOF
   # The script installs the post_CAVER_energies program 
   
   ./INSTALL -d dir
          
      -d <v> : Installation directory
      -h : help message
EOF
);

version=$(cat << EOF
	version: 1.0
	author: Javier Rodriguez-Salarichs
EOF
);


while getopts ":d:v:h" opt; do
  case $opt in
    d)
      install_dir=$OPTARG
      ;;
    \?)
      echo "Invalid option: -$OPTARG" >&2
      echo "$usage"
      exit 1;
      ;;
    v)
       echo "$version"
       exit 1;
       ;;
    h)
       echo "$usage"
       exit 1;
       ;;
    :)
      echo "Option -$OPTARG requires an argument." >&2
      exit 1;
      ;;
  esac
done

if [ -z $install_dir ];then
 install_dir="/usr/local/post_CAVER_energies"
fi

dir_len=`echo $install_dir|awk '{print length($0)}'`

if [ $dir_len -gt 72 ];then
 echo "installing directory can not be larger than 72 characters"
 exit -1
fi

echo "$install_dir"

dir=`pwd`

if [ `uname -o|grep "Linux"`  ]
then
 
awk -v var=$install_dir"/third-party/MGLTools-1.5.6/bin/pythonsh" '{if(NR==1){print "#!/usr/bin/env "var}else{print $0 }}' scripts/prepare_receptor-ipdb-opdbqt.py > scripts/prepare_receptor-ipdb-opdbqt_new.py && mv scripts/prepare_receptor-ipdb-opdbqt_new.py scripts/prepare_receptor-ipdb-opdbqt.py


 ./configure "--prefix="$install_dir
 make && make install

 cd $dir"/sources/third-party/parallel-20170622"
 mkdir $install_dir"/third-party"
 mkdir $install_dir"/third-party/parallel-20170622"
 ./configure "--prefix="$install_dir"/third-party/parallel-20170622"
 make && make install
 cd $dir

 if [ `uname -m|grep "x86_64"`  ]
 then
  cd $dir/sources/third-party/mgltools_x86_64Linux2_1.5.6/
 # mkdir $install_dir"/third-party"
  mkdir $install_dir"/third-party/MGLTools-1.5.6"
  ./install.sh -d $install_dir"/third-party/MGLTools-1.5.6"
  cd $dir
  
 else
  cd $dir/sources/third-party/mgltools_i86Linux2_1.5.6/
 # mkdir $install_dir"/third-party"
  mkdir $install_dir"/third-party/MGLTools-1.5.6"
  ./install.sh -d $install_dir"/third-party/MGLTools-1.5.6"
  cd $dir
 fi

 echo " Copying the licence ..."

 cp -vf AUTHORS COPYING README $install_dir"/."

fi 


echo "END OF THE INSTALLATION"

exit 0



